# Generated by Django 5.1.1 on 2026-03-10 09:25

import analysis.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200)),
                ('unique_code', models.CharField(default=analysis.models.generate_unique_code, max_length=6, unique=True)),
                ('frontal_image', models.ImageField(upload_to='uploads/frontal/')),
                ('left_lateral_image', models.ImageField(upload_to='uploads/left_lateral/')),
                ('right_lateral_image', models.ImageField(upload_to='uploads/right_lateral/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('mgi_score', models.IntegerField(blank=True, help_text='Modified Gingival Index (0-4)', null=True)),
                ('ohi_score', models.IntegerField(blank=True, help_text='Oral Hygiene Index (0-3)', null=True)),
                ('gei_score', models.IntegerField(blank=True, help_text='Gingival Enlargement Index (0-2)', null=True)),
                ('mgi_confidence', models.FloatField(blank=True, null=True)),
                ('ohi_confidence', models.FloatField(blank=True, null=True)),
                ('gei_confidence', models.FloatField(blank=True, null=True)),
                ('gradcam_frontal', models.ImageField(blank=True, null=True, upload_to='gradcam/')),
                ('gradcam_left', models.ImageField(blank=True, null=True, upload_to='gradcam/')),
                ('gradcam_right', models.ImageField(blank=True, null=True, upload_to='gradcam/')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Patient Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
