# Generated by Django 5.1.1 on 2026-03-19

import analysis.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('dentist', 'Dentist'), ('patient', 'Patient')], db_index=True, default='patient', max_length=20)),
                ('dentist_owner', models.ForeignKey(blank=True, help_text='For patient accounts, identifies the responsible dentist.', limit_choices_to={'role': 'dentist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='analysis.dentaluser')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200)),
                ('unique_code', models.CharField(default=analysis.models.generate_unique_code, max_length=6, unique=True)),
                ('frontal_image', models.ImageField(upload_to='uploads/frontal/')),
                ('left_lateral_image', models.ImageField(upload_to='uploads/left_lateral/')),
                ('right_lateral_image', models.ImageField(upload_to='uploads/right_lateral/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('mgi_score', models.IntegerField(blank=True, help_text='Modified Gingival Index (0-4)', null=True)),
                ('ohi_score', models.IntegerField(blank=True, help_text='Oral Hygiene Index (0-3)', null=True)),
                ('gei_score', models.IntegerField(blank=True, help_text='Gingival Enlargement Index (0-2)', null=True)),
                ('ai_mgi_score', models.IntegerField(blank=True, null=True)),
                ('ai_ohi_score', models.IntegerField(blank=True, null=True)),
                ('ai_gei_score', models.IntegerField(blank=True, null=True)),
                ('mgi_confidence', models.FloatField(blank=True, null=True)),
                ('ohi_confidence', models.FloatField(blank=True, null=True)),
                ('gei_confidence', models.FloatField(blank=True, null=True)),
                ('ai_mgi_confidence', models.FloatField(blank=True, null=True)),
                ('ai_ohi_confidence', models.FloatField(blank=True, null=True)),
                ('ai_gei_confidence', models.FloatField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('unreviewed', 'Unreviewed Reports'), ('approved', 'Approved Reports'), ('rejected', 'Rejected Reports')], db_index=True, default='unreviewed', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('dentist_note', models.TextField(blank=True, default='')),
                ('gradcam_frontal', models.ImageField(blank=True, null=True, upload_to='gradcam/')),
                ('gradcam_left', models.ImageField(blank=True, null=True, upload_to='gradcam/')),
                ('gradcam_right', models.ImageField(blank=True, null=True, upload_to='gradcam/')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who triggered the upload.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to='analysis.dentaluser')),
                ('dentist_owner', models.ForeignKey(blank=True, help_text='Dentist responsible for reviewing this report.', limit_choices_to={'role': 'dentist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dentist_reports', to='analysis.dentaluser')),
                ('patient_user', models.ForeignKey(blank=True, help_text='Patient account that owns this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_reports', to='analysis.dentaluser')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['dentist', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to='analysis.dentaluser')),
            ],
            options={
                'verbose_name_plural': 'Patient Analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dentist_owner', 'review_status', 'created_at'], name='analysis_pat_dentist_8ec29f_idx'), models.Index(fields=['patient_user', 'created_at'], name='analysis_pat_patient_0bc093_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_mgi_score', models.IntegerField(blank=True, null=True)),
                ('old_ohi_score', models.IntegerField(blank=True, null=True)),
                ('old_gei_score', models.IntegerField(blank=True, null=True)),
                ('new_mgi_score', models.IntegerField(blank=True, null=True)),
                ('new_ohi_score', models.IntegerField(blank=True, null=True)),
                ('new_gei_score', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='analysis.patientanalysis')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_revisions', to='analysis.dentaluser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
