# Generated by Django 6.0.3 on 2026-03-19 04:22

from django.db import migrations


def _safe_rename_or_create_indexes(apps, schema_editor):
    """
    Keep this migration idempotent across DBs that may already have either
    old index names, new index names, or no index names from prior resets.
    """
    PatientAnalysis = apps.get_model('analysis', 'PatientAnalysis')
    table = PatientAnalysis._meta.db_table

    constraints = schema_editor.connection.introspection.get_constraints(schema_editor.connection.cursor(), table)
    existing = set(constraints.keys())
    vendor = schema_editor.connection.vendor

    plan = [
        (
            'analysis_pat_dentist_8ec29f_idx',
            'analysis_pa_dentist_1ca651_idx',
            '("dentist_owner_id", "review_status", "created_at")',
        ),
        (
            'analysis_pat_patient_0bc093_idx',
            'analysis_pa_patient_1a442f_idx',
            '("patient_user_id", "created_at")',
        ),
    ]

    for old_name, new_name, column_sql in plan:
        # Already in the desired state.
        if new_name in existing:
            continue

        # Rename when the old index exists.
        if old_name in existing:
            if vendor == 'sqlite':
                # SQLite support for index renames varies by runtime version.
                schema_editor.execute(f'CREATE INDEX "{new_name}" ON "{table}" {column_sql}')
                schema_editor.execute(f'DROP INDEX "{old_name}"')
            else:
                schema_editor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')
            continue

        # Neither old nor new exists; create the expected index.
        schema_editor.execute(f'CREATE INDEX "{new_name}" ON "{table}" {column_sql}')


def _noop_reverse(apps, schema_editor):
    # Reverse behavior is intentionally a no-op for this stabilization migration.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_safe_rename_or_create_indexes, _noop_reverse),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='patientanalysis',
                    new_name='analysis_pa_dentist_1ca651_idx',
                    old_name='analysis_pat_dentist_8ec29f_idx',
                ),
                migrations.RenameIndex(
                    model_name='patientanalysis',
                    new_name='analysis_pa_patient_1a442f_idx',
                    old_name='analysis_pat_patient_0bc093_idx',
                ),
            ],
        ),
    ]
