# Generated by Django 6.0.3 on 2026-03-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_dentaluser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientanalysis',
            name='ai_plaque_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientanalysis',
            name='ai_plaque_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientanalysis',
            name='plaque_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientanalysis',
            name='plaque_score',
            field=models.IntegerField(blank=True, help_text='Plaque Level (Turesky-modified Quigley-Hein, 0-5)', null=True),
        ),
        migrations.AddField(
            model_name='reportrevision',
            name='new_plaque_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportrevision',
            name='old_plaque_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
