# Generated by Django 6.0.4 on 2026-04-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_patientanalysis_plaque_ratio_and_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientanalysis',
            name='gei_score',
            field=models.IntegerField(blank=True, help_text='Gingival Enlargement Index (0-3)', null=True),
        ),
    ]
