# Generated by Django 6.0.4 on 2026-04-16 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_alter_patientanalysis_gei_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('slots_proposed', 'Slots Proposed'), ('slot_selected', 'Slot Selected')], db_index=True, default='requested', max_length=30)),
                ('slot_option_1', models.DateTimeField(blank=True, null=True)),
                ('slot_option_2', models.DateTimeField(blank=True, null=True)),
                ('slot_option_3', models.DateTimeField(blank=True, null=True)),
                ('selected_slot', models.DateTimeField(blank=True, null=True)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dentist', models.ForeignKey(limit_choices_to={'role': 'dentist'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests_received', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dentist', 'status', 'created_at'], name='analysis_ap_dentist_f894cc_idx'), models.Index(fields=['patient', 'status', 'created_at'], name='analysis_ap_patient_d272c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='DentistSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dentist', models.ForeignKey(limit_choices_to={'role': 'dentist'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_suggestions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dentist', 'created_at'], name='analysis_de_dentist_7df0f7_idx'), models.Index(fields=['patient', 'created_at'], name='analysis_de_patient_0610ac_idx')],
            },
        ),
    ]
