# Generated by Django 6.0.4 on 2026-04-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_appointmentrequest_dentistsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientanalysis',
            name='review_status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('approved', 'Approved'), ('rejected', 'Edited')], db_index=True, default='unreviewed', max_length=20),
        ),
    ]
