# Generated by Django 6.0.4 on 2026-06-25 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_alter_patientanalysis_review_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentistImageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontal_requested', models.BooleanField(default=False)),
                ('left_lateral_requested', models.BooleanField(default=False)),
                ('right_lateral_requested', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frontal_image', models.ImageField(blank=True, null=True, upload_to='uploads/requests/frontal/')),
                ('left_lateral_image', models.ImageField(blank=True, null=True, upload_to='uploads/requests/left_lateral/')),
                ('right_lateral_image', models.ImageField(blank=True, null=True, upload_to='uploads/requests/right_lateral/')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dentist', models.ForeignKey(limit_choices_to={'role': 'dentist'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_image_requests', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_image_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['dentist', 'status', 'requested_at'], name='analysis_de_dentist_b3aa3a_idx'), models.Index(fields=['patient', 'status', 'requested_at'], name='analysis_de_patient_785296_idx')],
            },
        ),
    ]
